<?php
	$relativePath = '../../';
	$scripts = array(
		$relativePath.'assets/js/vendor/skrollr.menu.js',
		'js/script.js'
	);
	$styles = array('css/compiled/style.css');
	include($relativePath.'php/header.php');
?>

<header class="title">
	<h1>Skrollr Menu<a href="../../index.php"><span>➜</span> back</a></h1>
</header>

<div id="menu">
	<ul>
		<li><a id="link-1" href="#p1">Period 1</a></li>
		<li><a id="link-2" href="#p2">Period 2</a></li>
		<li><a id="link-3" href="#p3">Period 3</a></li>
		<li><a id="link-4" href="#p4">Period 4</a></li>
		<li><a id="link-5" href="#p5">Period 5</a></li>
		<li><a id="link-6" href="#p6">Period 6</a></li>
	</ul>
</div

<div id="skrollr-body">

	<div id="container">

		<div id="p1" class="period">
			<h2>Period 1</h2>
			<p>Kickstarter quinoa mumblecore keytar McSweeney's.  Kogi photo booth trust fund fixie American Apparel, sriracha ethical craft beer banjo.  XOXO pour-over Vice four loko, irony letterpress drinking vinegar fixie retro biodiesel ethical.  Kogi High Life vinyl Bushwick, seitan photo booth wolf.  Thundercats tote bag kitsch Banksy fap.  Bespoke Kickstarter Truffaut pug DINormcore 90's bicycle rights chillwave Kickstarter, American Apparel meggings Pinterest Cosby sweater pickled roof party.  Banh mi selfies food truck, you probably haven't heard of them Helvetica cornhole asymmetrical stumptown.  Small batch flexitarian meggings wayfarers, hashtag put a bird on it YOLO Wes Anderson dreamcatcher lo-fi tote bag disrupt before they sold out single-origin coffee gastropub.  +1 American Apparel ugh, Austin swag brunch chillwave fashion axe crucifix.  Single-origin coffee yr fashion axe authentic master cleanse tousled mumblecore beard, meh art party butcher drinking vinegar banh mi.  Kale chips PBR pop-up, Schlitz banjo Truffaut vinyl.  Distillery chambray hashtag street art occupy typewriter gentrify, VHS +1 XOXO art party biodiesel quinoa farm-to-table. mustache.  Vice before they sold out roof party yr gastropub pour-over.<p>
			<p>Kickstarter quinoa mumblecore keytar McSweeney's.  Kogi photo booth trust fund fixie American Apparel, sriracha ethical craft beer banjo.  XOXO pour-over Vice four loko, irony letterpress drinking vinegar fixie retro biodiesel ethical.  Kogi High Life vinyl Bushwick, seitan photo booth wolf.  Thundercats tote bag kitsch Banksy fap.  Bespoke Kickstarter Truffaut pug DINormcore 90's bicycle rights chillwave Kickstarter, American Apparel meggings Pinterest Cosby sweater pickled roof party.  Banh mi selfies food truck, you probably haven't heard of them Helvetica cornhole asymmetrical stumptown.  Small batch flexitarian meggings wayfarers, hashtag put a bird on it YOLO Wes Anderson dreamcatcher lo-fi tote bag disrupt before they sold out single-origin coffee gastropub.  +1 American Apparel ugh, Austin swag brunch chillwave fashion axe crucifix.  Single-origin coffee yr fashion axe authentic master cleanse tousled mumblecore beard, meh art party butcher drinking vinegar banh mi.  Kale chips PBR pop-up, Schlitz banjo Truffaut vinyl.  Distillery chambray hashtag street art occupy typewriter gentrify, VHS +1 XOXO art party biodiesel quinoa farm-to-table. mustache.  Vice before they sold out roof party yr gastropub pour-over.<p>
			<p>Kickstarter quinoa mumblecore keytar McSweeney's.  Kogi photo booth trust fund fixie American Apparel, sriracha ethical craft beer banjo.  XOXO pour-over Vice four loko, irony letterpress drinking vinegar fixie retro biodiesel ethical.  Kogi High Life vinyl Bushwick, seitan photo booth wolf.  Thundercats tote bag kitsch Banksy fap.  Bespoke Kickstarter Truffaut pug DINormcore 90's bicycle rights chillwave Kickstarter, American Apparel meggings Pinterest Cosby sweater pickled roof party.  Banh mi selfies food truck, you probably haven't heard of them Helvetica cornhole asymmetrical stumptown.  Small batch flexitarian meggings wayfarers, hashtag put a bird on it YOLO Wes Anderson dreamcatcher lo-fi tote bag disrupt before they sold out single-origin coffee gastropub.  +1 American Apparel ugh, Austin swag brunch chillwave fashion axe crucifix.  Single-origin coffee yr fashion axe authentic master cleanse tousled mumblecore beard, meh art party butcher drinking vinegar banh mi.  Kale chips PBR pop-up, Schlitz banjo Truffaut vinyl.  Distillery chambray hashtag street art occupy typewriter gentrify, VHS +1 XOXO art party biodiesel quinoa farm-to-table. mustache.  Vice before they sold out roof party yr gastropub pour-over.<p>
		</div>
		<div id="p2" class="period">
			<h2>Period 2</h2>
			<p>Kickstarter quinoa mumblecore keytar McSweeney's.  Kogi photo booth trust fund fixie American Apparel, sriracha ethical craft beer banjo.  XOXO pour-over Vice four loko, irony letterpress drinking vinegar fixie retro biodiesel ethical.  Kogi High Life vinyl Bushwick, seitan photo booth wolf.  Thundercats tote bag kitsch Banksy fap.  Bespoke Kickstarter Truffaut pug DINormcore 90's bicycle rights chillwave Kickstarter, American Apparel meggings Pinterest Cosby sweater pickled roof party.  Banh mi selfies food truck, you probably haven't heard of them Helvetica cornhole asymmetrical stumptown.  Small batch flexitarian meggings wayfarers, hashtag put a bird on it YOLO Wes Anderson dreamcatcher lo-fi tote bag disrupt before they sold out single-origin coffee gastropub.  +1 American Apparel ugh, Austin swag brunch chillwave fashion axe crucifix.  Single-origin coffee yr fashion axe authentic master cleanse tousled mumblecore beard, meh art party butcher drinking vinegar banh mi.  Kale chips PBR pop-up, Schlitz banjo Truffaut vinyl.  Distillery chambray hashtag street art occupy typewriter gentrify, VHS +1 XOXO art party biodiesel quinoa farm-to-table. mustache.  Vice before they sold out roof party yr gastropub pour-over.<p>
			<p>Kickstarter quinoa mumblecore keytar McSweeney's.  Kogi photo booth trust fund fixie American Apparel, sriracha ethical craft beer banjo.  XOXO pour-over Vice four loko, irony letterpress drinking vinegar fixie retro biodiesel ethical.  Kogi High Life vinyl Bushwick, seitan photo booth wolf.  Thundercats tote bag kitsch Banksy fap.  Bespoke Kickstarter Truffaut pug DINormcore 90's bicycle rights chillwave Kickstarter, American Apparel meggings Pinterest Cosby sweater pickled roof party.  Banh mi selfies food truck, you probably haven't heard of them Helvetica cornhole asymmetrical stumptown.  Small batch flexitarian meggings wayfarers, hashtag put a bird on it YOLO Wes Anderson dreamcatcher lo-fi tote bag disrupt before they sold out single-origin coffee gastropub.  +1 American Apparel ugh, Austin swag brunch chillwave fashion axe crucifix.  Single-origin coffee yr fashion axe authentic master cleanse tousled mumblecore beard, meh art party butcher drinking vinegar banh mi.  Kale chips PBR pop-up, Schlitz banjo Truffaut vinyl.  Distillery chambray hashtag street art occupy typewriter gentrify, VHS +1 XOXO art party biodiesel quinoa farm-to-table. mustache.  Vice before they sold out roof party yr gastropub pour-over.<p>
			<p>Kickstarter quinoa mumblecore keytar McSweeney's.  Kogi photo booth trust fund fixie American Apparel, sriracha ethical craft beer banjo.  XOXO pour-over Vice four loko, irony letterpress drinking vinegar fixie retro biodiesel ethical.  Kogi High Life vinyl Bushwick, seitan photo booth wolf.  Thundercats tote bag kitsch Banksy fap.  Bespoke Kickstarter Truffaut pug DINormcore 90's bicycle rights chillwave Kickstarter, American Apparel meggings Pinterest Cosby sweater pickled roof party.  Banh mi selfies food truck, you probably haven't heard of them Helvetica cornhole asymmetrical stumptown.  Small batch flexitarian meggings wayfarers, hashtag put a bird on it YOLO Wes Anderson dreamcatcher lo-fi tote bag disrupt before they sold out single-origin coffee gastropub.  +1 American Apparel ugh, Austin swag brunch chillwave fashion axe crucifix.  Single-origin coffee yr fashion axe authentic master cleanse tousled mumblecore beard, meh art party butcher drinking vinegar banh mi.  Kale chips PBR pop-up, Schlitz banjo Truffaut vinyl.  Distillery chambray hashtag street art occupy typewriter gentrify, VHS +1 XOXO art party biodiesel quinoa farm-to-table. mustache.  Vice before they sold out roof party yr gastropub pour-over.<p>
		</div>
		<div id="p3" class="period">
			<h2>Period 3</h2>
			<p>Blue Bottle beard pug bitters salvia.  Before they sold out Banksy asymmetrical, meh twee put a bird on it Thundercats crucifix photo booth.  DIY stumptown ethnic YOLO biodiesel, messenger bag fap Wes Anderson Thundercats craft beer jean shorts mixtape cliche.  Tonx gastropub meggings photo booth.  Kitsch small batch mlkshk, PBR art party narwhal 8-bit whatever post-ironic.  You probably haven't heard of them selvage mumblecore, Intelligentsia blog crucifix typewriter literally YOLO 8-bit 90's cornhole Schlitz Tonx.  Next level High Life XOXO, skateboard squid synth typewriter trust fund letterpress gluten-free ethical.<p>
			<p>Blue Bottle beard pug bitters salvia.  Before they sold out Banksy asymmetrical, meh twee put a bird on it Thundercats crucifix photo booth.  DIY stumptown ethnic YOLO biodiesel, messenger bag fap Wes Anderson Thundercats craft beer jean shorts mixtape cliche.  Tonx gastropub meggings photo booth.  Kitsch small batch mlkshk, PBR art party narwhal 8-bit whatever post-ironic.  You probably haven't heard of them selvage mumblecore, Intelligentsia blog crucifix typewriter literally YOLO 8-bit 90's cornhole Schlitz Tonx.  Next level High Life XOXO, skateboard squid synth typewriter trust fund letterpress gluten-free ethical.<p>
			<p>Blue Bottle beard pug bitters salvia.  Before they sold out Banksy asymmetrical, meh twee put a bird on it Thundercats crucifix photo booth.  DIY stumptown ethnic YOLO biodiesel, messenger bag fap Wes Anderson Thundercats craft beer jean shorts mixtape cliche.  Tonx gastropub meggings photo booth.  Kitsch small batch mlkshk, PBR art party narwhal 8-bit whatever post-ironic.  You probably haven't heard of them selvage mumblecore, Intelligentsia blog crucifix typewriter literally YOLO 8-bit 90's cornhole Schlitz Tonx.  Next level High Life XOXO, skateboard squid synth typewriter trust fund letterpress gluten-free ethical.<p>
		</div>
		<div id="p4" class="period">
			<h2>Period 4</h2>
			<p>McSweeney's Thundercats locavore salvia, literally flannel cred before they sold out cornhole pour-over Neutra mixtape Wes Anderson quinoa Vice.  Normcore 8-bit yr, keytar disrupt Marfa typewriter.  3 wolf moon VHS seitan gastropub.  Art party XOXO bicycle rights keytar.  Hashtag hoodie Pinterest ethical pop-up slow-carb church-key, 3 wolf moon selvage ennui.  Brunch raw denim pug, dreamcatcher +1 post-ironic 90's before they sold out Brooklyn cornhole aesthetic art party swag.  Organic swag dreamcatcher meh Odd Future, cliche fap roof party sriracha beard Williamsburg Blue Bottle.<p>
			<p>McSweeney's Thundercats locavore salvia, literally flannel cred before they sold out cornhole pour-over Neutra mixtape Wes Anderson quinoa Vice.  Normcore 8-bit yr, keytar disrupt Marfa typewriter.  3 wolf moon VHS seitan gastropub.  Art party XOXO bicycle rights keytar.  Hashtag hoodie Pinterest ethical pop-up slow-carb church-key, 3 wolf moon selvage ennui.  Brunch raw denim pug, dreamcatcher +1 post-ironic 90's before they sold out Brooklyn cornhole aesthetic art party swag.  Organic swag dreamcatcher meh Odd Future, cliche fap roof party sriracha beard Williamsburg Blue Bottle.<p>
			<p>McSweeney's Thundercats locavore salvia, literally flannel cred before they sold out cornhole pour-over Neutra mixtape Wes Anderson quinoa Vice.  Normcore 8-bit yr, keytar disrupt Marfa typewriter.  3 wolf moon VHS seitan gastropub.  Art party XOXO bicycle rights keytar.  Hashtag hoodie Pinterest ethical pop-up slow-carb church-key, 3 wolf moon selvage ennui.  Brunch raw denim pug, dreamcatcher +1 post-ironic 90's before they sold out Brooklyn cornhole aesthetic art party swag.  Organic swag dreamcatcher meh Odd Future, cliche fap roof party sriracha beard Williamsburg Blue Bottle.<p>
		</div>
		<div id="p5" class="period">
			<h2>Period 5</h2>
			<p>Authentic Williamsburg ethnic photo booth, keffiyeh salvia banh mi Etsy post-ironic.  Wayfarers keytar Tonx, sartorial letterpress master cleanse typewriter crucifix direct trade  food truck tattooed tousled Shoreditch.  Disrupt mustache cornhole irony Tumblr, gastropub Echo Park trust fund pug drinking vinegar Truffaut American Apparel salvia viral.  Put a bird on it blog before they sold out, pickled Vice normcore asymmetrical.  Helvetica pour-over roof party flannel.  Schlitz cardigan keffiyeh typewriter roof party, hashtag Pitchfork put a bird on it PBR sartorial XOXO.  Kickstarter hoodie small batch freegan 3 wolf moon next level.<p>
			<p>Authentic Williamsburg ethnic photo booth, keffiyeh salvia banh mi Etsy post-ironic.  Wayfarers keytar Tonx, sartorial letterpress master cleanse typewriter crucifix direct trade  food truck tattooed tousled Shoreditch.  Disrupt mustache cornhole irony Tumblr, gastropub Echo Park trust fund pug drinking vinegar Truffaut American Apparel salvia viral.  Put a bird on it blog before they sold out, pickled Vice normcore asymmetrical.  Helvetica pour-over roof party flannel.  Schlitz cardigan keffiyeh typewriter roof party, hashtag Pitchfork put a bird on it PBR sartorial XOXO.  Kickstarter hoodie small batch freegan 3 wolf moon next level.<p>
			<p>Authentic Williamsburg ethnic photo booth, keffiyeh salvia banh mi Etsy post-ironic.  Wayfarers keytar Tonx, sartorial letterpress master cleanse typewriter crucifix direct trade  food truck tattooed tousled Shoreditch.  Disrupt mustache cornhole irony Tumblr, gastropub Echo Park trust fund pug drinking vinegar Truffaut American Apparel salvia viral.  Put a bird on it blog before they sold out, pickled Vice normcore asymmetrical.  Helvetica pour-over roof party flannel.  Schlitz cardigan keffiyeh typewriter roof party, hashtag Pitchfork put a bird on it PBR sartorial XOXO.  Kickstarter hoodie small batch freegan 3 wolf moon next level.<p>
		</div>
		<div id="p6" class="period">
			<h2>Period 6</h2>
			<p>Wolf single-origin coffee American Apparel, letterpress Tumblr Truffaut meh Neutra blog Banksy banh mi cred.  Wes Anderson gentrify freegan Neutra mumblecore High Life.  Post-ironic readymade swag, letterpress sartorial viral tofu mlkshk.  Authentic distillery narwhal, skateboard banh mi keytar chambray mumblecore Blue Bottle.  Single-origin coffee chambray pickled, VHS kale chips flexitarian literally viral street art umami hella Wes Anderson.  Before they sold out church-key gluten-free, kale chips swag organic banjo pickled selfies whatever.  Church-key salvia selfies hella, Carles hoodie mixtape XOXO Wes Anderson small batch pickled.<p>
			<p>Wolf single-origin coffee American Apparel, letterpress Tumblr Truffaut meh Neutra blog Banksy banh mi cred.  Wes Anderson gentrify freegan Neutra mumblecore High Life.  Post-ironic readymade swag, letterpress sartorial viral tofu mlkshk.  Authentic distillery narwhal, skateboard banh mi keytar chambray mumblecore Blue Bottle.  Single-origin coffee chambray pickled, VHS kale chips flexitarian literally viral street art umami hella Wes Anderson.  Before they sold out church-key gluten-free, kale chips swag organic banjo pickled selfies whatever.  Church-key salvia selfies hella, Carles hoodie mixtape XOXO Wes Anderson small batch pickled.<p>
			<p>Wolf single-origin coffee American Apparel, letterpress Tumblr Truffaut meh Neutra blog Banksy banh mi cred.  Wes Anderson gentrify freegan Neutra mumblecore High Life.  Post-ironic readymade swag, letterpress sartorial viral tofu mlkshk.  Authentic distillery narwhal, skateboard banh mi keytar chambray mumblecore Blue Bottle.  Single-origin coffee chambray pickled, VHS kale chips flexitarian literally viral street art umami hella Wes Anderson.  Before they sold out church-key gluten-free, kale chips swag organic banjo pickled selfies whatever.  Church-key salvia selfies hella, Carles hoodie mixtape XOXO Wes Anderson small batch pickled.<p>
		</div>

	</div>
</div>


<?php
	include($relativePath.'php/footer.php');
?>